matrix: 
    include: 
    -   language: csharp 
        os: osx
        mono: none
        dotnet: 2.1.300
        solution: DummyBackendDotNetCore/DummyBackendDotNetCore.sln 
        env: MSBUILDENSURESTDOUTFORTASKPROCESSES=1
        branches:
               only:
                  - master
                  - unity_branch
                  - csharp_branch
        script: 
            - dotnet restore
            #- msbuild /p:Configuration=Release /p:Platform=x64 DummyBackendDotNetCore/DummyBackendDotNetCore.sln
            - dotnet build /DummyBackendDotNetCore/DummyBackendDotNetCore
            - dotnet build /DummyBackendDotNetCore/DummyBackendDotNetCore_Test
            - dotnet test /DummyBackendDotNetCore/DummyBackendDotNetCore_Test.csproj --verbosity=normal /nodeReuse:false
            #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./DummyBackendDotNetCore/DummyBackendDotNetCore_Test/bin/x64/Release/netcoreapp2.1/DummyBackendDotNetCore_Test.dll
    
