language: csharp
dist: trusty
mono: none
dotnet: 2.1

branches:
  only:
  - master
  - xunit_dotnet_core

install:
- dotnet restore

script:
- dotnet build dotnetcore/dotnetcore.sln -v n
- dotnet test dotnetcore/dotnetcore_test/dotnetcore_test.csproj -v n

