language: csharp
dist: trusty
mono: none
dotnet: 2.1

branches:
  only:
  - master
  - xunit_dotnet_core

before_install:
- chmod a+x ./Travis/tag.sh
- chmod a+x ./Travis/tag_incrementer.sh
  
install:
- dotnet restore dotnetcore/dotnetcore.sln -v n

script:
- dotnet build dotnetcore/dotnetcore.sln -v n
- dotnet test dotnetcore/dotnetcore_test/dotnetcore_test.csproj -v n
- ls -l
- cd "/home/travis/build/kernerdev/travis-ci-test-with-unity/"
- ls -l
- ./Travis/tag.sh