dist: trusty
sudo: required

branches:
  only:
  - master
  - xunit_dotnet_core

before_install:
- chmod a+x ./Travis/tag.sh
- chmod a+x ./Travis/tag_incrementer.sh
- cat version.txt
- ./Travis/tag.sh