matrix: 
    include: 
    -   language: csharp 
        os: osx
        mono: latest 
        solution: DummyBackendDotNetCore/DummyBackendDotNetCore.sln 
        
        branches:
               only:
                  - master
                  - unity_branch
                  - csharp_branch
        install: 
            - nuget restore DummyBackendDotNetCore/DummyBackendDotNetCore.sln 
            - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner 
        script: 
            - xbuild /p:Configuration=Release DummyBackendDotNetCore/DummyBackendDotNetCore.sln 
            - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./DummyBackendDotNetCore/DummyBackendDotNetCore_Test/bin/Release/netcoreapp2.1/DummyBackendDotNetCore_Test.dll
    
