matrix: 
    include: 
    -   language: csharp 
        os: osx
        mono: latest 
        solution: DummyBackendDotNetStandard/DummyBackendDotNetStandard.sln 
        
        branches:
               only:
                  - master
                  - unity_branch
                  - csharp_branch
        install: 
            - nuget restore DummyBackendDotNetStandard/DummyBackendDotNetStandard.sln 
            - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner 
        script: 
            - xbuild /p:Configuration=Release DummyBackendDotNetStandard/DummyBackendDotNetStandard.sln 
            - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./DummyBackendDotNetStandard/DummyBackendDotNetStandard_Test/bin/Release/MyProject.Tests.dll
    
