dist: trusty
sudo: required

branches:
  only:
  - master
  - xunit_dotnet_core

before_install:
- chmod a+x ./Travis/tag.sh
- chmod a+x ./Travis/tag_incrementer.sh
- pwd
- ls -l
- cat version.txt
- sudo ./Travis/tag.sh
- cd Travis
- pwd
- ls -l